#!/bin/sh

if ! updates=$(yay -Qum 2> /dev/null | wc -l); then
# if ! updates=$(paru -Qum 2> /dev/null | wc -l); then
# if ! updates=$(cower -u 2> /dev/null | wc -l); then
# if ! updates=$(trizen -Su --aur --quiet | wc -l); then
# if ! updates=$(pikaur -Qua 2> /dev/null | wc -l); then
# if ! updates=$(rua upgrade --printonly 2> /dev/null | wc -l); then
    updates=0
fi

if [ "$updates" -gt 0 ]; then
    notify-send "New updates available for Arch Linux" "$updates aur packages" \
	-u NORMAL -t 2000 -i /usr/share/icons/Papirus/48x48/categories/org.kde.archUpdate.svg
else
    echo ""
fi
