#!/usr/bin/env bash

turn_on_wifi() {
  if ! nmcli radio wifi | grep -q "enabled"; then
    nmcli radio wifi on || die "Failed to turn on Wi-Fi"
  fi
}

has() {
  local verbose=false
  if [[ $1 == '-v' ]]; then
    verbose=true
    shift
  fi
  for c in "$@"; do c="${c%% *}"
    if ! command -v "$c" &> /dev/null; then
      [[ "$verbose" == true ]] && err "$c not found"
      return 1
    fi
  done
}

err() {
  printf '\e[31m%s\e[0m\n' "$*" >&2
}

die() {
  (( $# > 0 )) && err "$*"
  exit 1
}

# Turn on Wi-Fi before searching for connections
turn_on_wifi

has -v nmcli fzf || die

nmcli -f 'BSSID,SIGNAL,BARS,SECURITY,FREQ,SSID' --color yes device wifi |
# nmcli -colors yes device wifi list | tail -n +2 | grep -v '^  *\B--\B' | sed 's/^ *\*//' |
  fzf \
  --with-nth=2.. \
  --ansi \
  --cycle \
  --inline-info \
  --header-lines=1 \
  --bind="enter:execute:nmcli device wifi connect {1}"
