#!/bin/bash

password_file=~/.password_file

icon_create=""
icon_copy=""

create_password() {
    read -p "Enter the name of the service: " service
    read -p "Enter the password: " password
    echo "$service:$password" >> $password_file
    echo "Password created!"
    dunstify -a "password_manager" -u low "$service" "Password Created" 
    echo $password | xsel -b
}

copy_password() {
    selected_password=$(echo -e "Create new password\n$(grep -v "^#" $password_file | cut -d ':' -f 1)" | fzf --prompt "Select a service> " --bind "ctrl-a:select-all")
    if [[ $selected_password == "Create new password" ]]; then
        create_password
    else
        service=$selected_password
        password=$(grep -w $service $password_file | cut -d ':' -f 2)
        echo $password | xsel -b
        dunstify -a "password_manager" -u low "$service" "Password Copied"
    fi
}

copy_password
