#!/bin/bash

# script for generating qr code
# https://github.com/aayushrathor

if [ "$1" == "--rofi" ]; then
  input=$(rofi -dmenu -i -l 0 -p "QR Input:" -theme-str 'entry { placeholder: "Hello World"; placeholder-color: grey;}')
else
  input=$1
fi
output="/tmp/qrgen.txt"

if [ -z "$input" ]; then
  echo "Enter Some Text";
  exit 1;
else
  qrencode -t UTF8 -c "$input" -o $output 
  if [ $? -ne 0 ]; then
    echo "Error: Failed to generate QR code."
    exit 1
  else
    cat $output
    notify-send -t 2000 "qrencode" "QR Generated 👍"
  fi
fi
