#!/bin/sh

if ! updates=$(checkupdates 2> /dev/null | wc -l ); then
    updates=0
fi

if [ "$updates" -gt 0 ]; then
    notify-send "New updates available for Arch Linux" "$updates pacman packages" \
	    -u NORMAL -t 2000 -i /usr/share/icons/Papirus/48x48/categories/org.kde.archUpdate.svg
else
    notify-send "Arch Linux is upto date" "No update require" \
	    -u NORMAL -t 2000 -i /usr/share/icons/Papirus/48x48/categories/org.kde.archUpdate.svg
fi
