#!/usr/bin/env zsh
# George Ornbo (shapeshed) http://shapeshed.com
# License - http://unlicense.org
#
# Fixes a corrupt .zsh_history file

mv ~/zsh/.zhistory ~/zsh/.zhistory_bad
strings ~/zsh/.zhistory_bad > ~/zsh/.zhistory
fc -R ~/zsh/.zhistory
rm ~/zsh/.zhistory_bad

echo "#########################################"
echo "#                  DONE                 #"
echo "#########################################"

