#!/bin/bash
#[[ ! -z "$@" ]] && (gh issue create --repo aayushrathor/db --label "cli" --title "$@" --body "" | sed -e 's/github.com\/aayushrathor\/db\/issues/i.aayushrathor.me\/i/g') || (echo "Forgot URL?"; exit 1)

rofin=`rofi -dmenu -i -l 0 -p "URL shortner"`

if [ -z $rofin ]; then
    echo "Forgot URL?";
    exit 1;
else
    URL=$(gh issue create --repo aayushrathor/db --label "cli" --title "$rofin" --body "" | sed -e 's/github.com\/aayushrathor\/db\/issues/i.aayushrathor.me\/i/g' | tr -d '\n')
    echo "$(date -I) -- $rofin -- $URL" >> ~/Desktop/temp/url_short.txt
    notify-send "Shortend URL: $URL"
    echo $URL | tr -d '\n' | xclip -sel clip -i $@
fi
