#!/bin/bash

PL=$(playerctl -l | tail -n 1)    # lists all working media players
PLST=$(playerctl status)    # get current status of media(paused|playing|etc||)
MPC=$(mpc current)

if [[ -z "$PL" && -z "$MPC" ]]; then    # checking if there's NO players active
	echo "No music ¯\_(ツ)_/¯"    # no media OUTPUT
else
        if [[ "$PLST" == "Playing" && -z "$MPC" ]]; then # if_block in if_block :|
		echo $(playerctl metadata artist): $(playerctl metadata title)    # edit this to fit yourself, default OUTPUT is: "artist: song."
	elif [[ -z "$MPC" && "$PLST" == "Paused" ]]; then
		echo "Paused, but ready to go :D"
	elif [[ -n "$MPC" ]]; then
		echo $MPC
	else
		echo "Play some music :D" 
	fi
fi
