#!/bin/sh

padding=$( bspc config window_gap )

# Show/hide polybar
if pgrep "polybar"; then
	polybar-msg cmd toggle
	notify-send "polybar toggled" -u NORMAL -t 1500
else
    ~/.config/polybar/launch.sh &
fi

bspc config window_gap $padding
