ipc_socket = true

[colors.bright]
black = "#666666"
blue = "#7aa6da"
cyan = "#70c0b1"
green = "#b9ca4a"
magenta = "#c397d8"
red = "#d54e53"
white = "#eaeaea"
yellow = "#e7c547"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.hints.end]
background = "#191919"
foreground = "#f1fa8c"

[colors.hints.start]
background = "#f1fa8c"
foreground = "#282a36"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "#1d1f21"
blue = "#81a2be"
cyan = "#8abeb7"
green = "#b5bd68"
magenta = "#b294bb"
red = "#cc6666"
white = "#c5c8c6"
yellow = "#f0c674"

[colors.primary]
background = "0x000000"
bright_foreground = "#ffffff"
foreground = "#f0f0f0"

# [colors.search."colors.footer_bar"]
# background = "#282a36"
# foreground = "#f8f8f2"

[colors.search.focused_match]
background = "#ffb86c"
foreground = "#44475a"

[colors.search.matches]
background = "#50fa7b"
foreground = "#44475a"

[colors.selection]
background = "#44475a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[font]
size = 14

[font.bold]
family = "Operator Mono"
style = "Bold"

[font.italic]
family = "Operator Mono"
style = "Bold"

[font.normal]
family = "Operator Mono"
style = "Bold"

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
opacity = 1.0

[window.dimensions]
columns = 133
lines = 40

[window.padding]
x = 6
y = 4
