#! /bin/sh
#  __                                                   
# |  \                                                  
# | ▓▓____   _______  ______  __   __   __ ______ ____  
# | ▓▓    \ /       \/      \|  \ |  \ |  \      \    \ 
# | ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓ | ▓▓ | ▓▓ ▓▓▓▓▓▓\▓▓▓▓\
# | ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ | ▓▓ | ▓▓ ▓▓ | ▓▓ | ▓▓
# | ▓▓__/ ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓_/ ▓▓_/ ▓▓ ▓▓ | ▓▓ | ▓▓
# | ▓▓    ▓▓       ▓▓ ▓▓    ▓▓\▓▓   ▓▓   ▓▓ ▓▓ | ▓▓ | ▓▓
#  \▓▓▓▓▓▓▓ \▓▓▓▓▓▓▓| ▓▓▓▓▓▓▓  \▓▓▓▓▓\▓▓▓▓ \▓▓  \▓▓  \▓▓
#                   | ▓▓                                
#                   | ▓▓                                
#                    \▓▓                                

pgrep -x sxhkd > /dev/null || sxhkd &
# Notifications
killall dunst
dunst --config $HOME/.config/dunst/dunstrc &

# increase keyrate
keybitrate &

bspc monitor -d I II III IV V VI VII VIII

bspc config window_gap          4
bspc config top_padding         32
bspc config bottom_padding      32
# bspc config right_padding       4
# bspc config left_padding        4

# This prevents from loading multiple times the same options on reload
bspc rule -r "*"

#ratio
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#border
bspc config border_width          1 
bspc config active_border_color 	"#000000"
bspc config focused_border_color  "#076678"
bspc config normal_border_color 	"#000000"

notify-send -a bspwm -u NORMAL -t 3000 "bspc configs set"

#rule
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave-browser desktop='^2'
bspc rule -a Google-chrome desktop='^2'
bspc rule -a "Vivaldi-stable" desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a "Thunar" state=floating
bspc rule -a gnome-calculator state=floating
bspc rule -a "discord" desktop='^8'
bspc rula -a "YouTube Music" desktop='^6' state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Lxappearance state=floating

notify-send -a bspwm -u NORMAL -t 3000 "bspc rules set"

#auto-start
zsh ~/.fehbg &> /dev/null 
zsh $HOME/.config/polybar/launch.sh &

#clipboardManager
greenclip daemon &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# gnome-keyrings
/usr/bin/gnome-keyring-daemon --start --components=secrets &

#picom --config $HOME/.config/picom/picom.conf
picom --experimental-backend --config $HOME/.config/picom/picom.conf &

# Network Applet
nm-applet --indicator &

#conky
pkill -9 conky
conky -c $HOME/.config/conky/Mimosa-Dark/Mimosa.conf &> /dev/null 

# xfce4-power-manager
xfce4-power-manager --daemon &

# kde-connect
indicator-kdeconnect &

# redshift bluelightfilter
# pkill -9 redshift
# zsh $HOME/scripts/redshift.sh &

notify-send -a bspwm -u NORMAL -t 3000 "bspc autostart applications"

#notify
notify-send -a bspwm -u NORMAL -t 3000 "here we go ... "
