#!/usr/bin/env bash

## launch waybar with alt config

CONFIG="/home/aayush/.config/waybar/config.json"
STYLE="/home/aayush/.config/waybar/style.css"

if [[ ! $(pidof waybar) ]]; then
	waybar --bar main-bar --log-level error --config ${CONFIG} --style ${STYLE}
fi
